# Generated by Django 5.2 on 2026-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
