# Generated by Django 5.2 on 2026-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='posts/archivos/'),
        ),
    ]
