# Generated by Django 5.2 on 2026-07-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='peso',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
